// <auto-generated />
using System;
using BuckingMachine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuckingMachine.Infrastructure.Migrations
{
    [DbContext(typeof(BuckingMachineDbContext))]
    partial class BuckingMachineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BuckingMachine.Domain.Entities.ParameterData", b =>
                {
                    b.Property<int>("ParameterDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ParameterDataId"));

                    b.Property<int>("AmountCycleMovements")
                        .HasColumnType("int");

                    b.Property<double>("BreakTimeHoldPos")
                        .HasColumnType("double");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("OperationModeMainDrives")
                        .HasColumnType("int");

                    b.Property<int>("OperationModeSideDrives")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("ReleaseTimeHoldPos")
                        .HasColumnType("double");

                    b.Property<double>("TargetPosMainDrives")
                        .HasColumnType("double");

                    b.Property<double>("TargetPosSideDrives")
                        .HasColumnType("double");

                    b.Property<double>("TargetTorqueMainDrives")
                        .HasColumnType("double");

                    b.Property<double>("TargetTorqueSideDrives")
                        .HasColumnType("double");

                    b.Property<double>("TargetVelocityMainDrives")
                        .HasColumnType("double");

                    b.Property<double>("TargetVelocitySideDrives")
                        .HasColumnType("double");

                    b.HasKey("ParameterDataId");

                    b.ToTable("ParameterData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
