// <auto-generated />
using System;
using BuckingMachine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuckingMachine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BuckingMachineDbContext))]
    [Migration("20260803082332_UpdatedDomainModel")]
    partial class UpdatedDomainModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BuckingMachine.Domain.Entities.Alarm", b =>
                {
                    b.Property<int>("AlarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlarmId");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("BuckingMachine.Domain.Entities.BuckingMachine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("BuckingMachine.Domain.Entities.MachineCycle", b =>
                {
                    b.Property<int>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParameterDataId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusDataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CycleId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ParameterDataId");

                    b.HasIndex("StatusDataId");

                    b.ToTable("MachineCycles");
                });

            modelBuilder.Entity("BuckingMachine.Domain.Entities.Operator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLoggedIn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OperatorId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("BuckingMachine.Domain.Entities.ParameterData", b =>
                {
                    b.Property<int>("ParameterDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountCycleMovements")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BreakTimeHoldPos")
                        .HasColumnType("REAL");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationModeMainDrives")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationModeSideDrives")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ReleaseTimeHoldPos")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetPosMainDrives")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetPosSideDrives")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetTorqueMainDrives")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetTorqueSideDrives")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetVelocityMainDrives")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetVelocitySideDrives")
                        .HasColumnType("REAL");

                    b.HasKey("ParameterDataId");

                    b.HasIndex("MachineId");

                    b.ToTable("ParameterData");
                });

            modelBuilder.Entity("BuckingMachine.Domain.Entities.StatusData", b =>
                {
                    b.Property<int>("StatusDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualPosMainDrives")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualPosSideDrives")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualTorqueMainDrives")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualTorqueSideDrives")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualVelocityMainDrives")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualVelocitySideDrives")
                        .HasColumnType("REAL");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotionState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationModeMainDrives")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationModeSideDrives")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("StatusDataId");

                    b.HasIndex("MachineId");

                    b.ToTable("StatusData");
                });

            modelBuilder.Entity("BuckingMachine.Domain.Entities.MachineCycle", b =>
                {
                    b.HasOne("BuckingMachine.Domain.Entities.BuckingMachine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuckingMachine.Domain.Entities.ParameterData", "ParameterData")
                        .WithMany()
                        .HasForeignKey("ParameterDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuckingMachine.Domain.Entities.StatusData", "StatusData")
                        .WithMany()
                        .HasForeignKey("StatusDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParameterData");

                    b.Navigation("StatusData");
                });

            modelBuilder.Entity("BuckingMachine.Domain.Entities.ParameterData", b =>
                {
                    b.HasOne("BuckingMachine.Domain.Entities.BuckingMachine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BuckingMachine.Domain.Entities.StatusData", b =>
                {
                    b.HasOne("BuckingMachine.Domain.Entities.BuckingMachine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
