<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuckingMachine.Application\BuckingMachine.Application.csproj" />
    <ProjectReference Include="..\BuckingMachine.Domain\BuckingMachine.Domain.csproj" />
  </ItemGroup>

</Project>
